# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b81c86ade8d415392f69a924a68ea424d4e400e44c7e3a42a721f5f5b3df791706f336a26afcedf8c6a0c4e28e9c7e84ac94627f28244164cc9369c9fff227a

test:
  secret_key_base: 2340ad132e040e8fced7b99429ecb5ae970fdf0155649bafd5b4bbffc9164cd913ab1f724643ec2f7536ed7a7ff0089126e5597493801d1c4d977355c9fb3607

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
